/*
 * Copyright (C) Sandra Sáez Raspeño - All Rights Reserved
 *
 * This file is part of Cellsignals.
 *
 * All information contained in this package is, and remains the property of
 * Sandra Sáez Raspeño. Copy and distribution of CellSignals or any result
 * generated by it is strictly forbidden unless prior written permission is
 * obtained from Sandra Sáez Raspeño.
 */

/**********************************************************************/
/*                                                                    */
/*                    CSELL CLASS DEFINITION                          */
/*                                                                    */
/**********************************************************************/

#ifndef CSCELL_H
#define CSCELL_H

#include "GCell.h"
#include <map>

class CSCell: public GCell {
 private:
  std::map<int,double> local_signals;

 public:

 /************************* Constructors ******************************/
  
  CSCell() { local_signals = std::map<int,double>(); }
  CSCell(std::map<int,double> signalMap) : local_signals(signalMap) {}

  
 /********************** Getters and Setters **************************/
  
  std::map<int,double> getSignalsMap();


 /*********************** Auxiliary functions *************************/

  bool _existSignal(int id);
  unsigned int _getTimer(int signal_id);
  void _setTimer(int signal_id, unsigned int time);
  
 /********************* Virtual member functions **********************/
  
  double getValue(int signal_id);
  void setValue(int signal_id, double concentration);
  void insertSignal(int id);
  void deleteSignal(int id);
  void incSignal(int id, double concentration);
  void decSignal(int id, double concentration);
};

#endif /* CSCELL_H */
