/*
 * Copyright (C) Sandra Sáez Raspeño - All Rights Reserved
 *
 * This file is part of Cellsignals.
 *
 * All information contained in this package is, and remains the property of
 * Sandra Sáez Raspeño. Copy and distribution of CellSignals or any result
 * generated by it is strictly forbidden unless prior written permission is
 * obtained from Sandra Sáez Raspeño.
 */

/**********************************************************************/
/*                                                                    */
/*                   DBCELL CLASS DEFINITION                          */
/*                                                                    */
/**********************************************************************/

#include "GCell.h"
#include <map>
#include <vector>

class DBCell: public GCell {
 private:
  std::map<int,std::vector<unsigned int> > local_signals;

 public:

 /************************* Constructors ******************************/
  
  DBCell() { local_signals = std::map<int,std::vector<unsigned int> >(); }
 DBCell(std::map<int,std::vector<unsigned int> > signalMap) : local_signals(signalMap) {}

  
 /********************** Getters and Setters **************************/
  
  std::map<int,std::vector<unsigned int> > getSignalsMap();
  
 /*********************** Auxiliary functions *************************/

  bool _existSignal(int id);
  unsigned int _getTimer(int signal_id);
 void _setTimer(int signal_id, unsigned int time);
  
 /********************* Virtual member functions **********************/
  
  double getValue(int signal_id);
  void setValue(int signal_id, double concentration);
  void insertSignal(int id);
  void deleteSignal(int id);
  void incSignal(int id, double concentration);
  void decSignal(int id, double concentration);
};
