/*
 * Copyright (C) Sandra Sáez Raspeño - All Rights Reserved
 *
 * This file is part of Cellsignals.
 *
 * All information contained in this package is, and remains the property of
 * Sandra Sáez Raspeño. Copy and distribution of CellSignals or any result
 * generated by it is strictly forbidden unless prior written permission is
 * obtained from Sandra Sáez Raspeño.
 */

/**********************************************************************/
/*                                                                    */
/*                   DPCELL CLASS DEFINITION                          */
/*                                                                    */
/**********************************************************************/

// Class that represents a digital proportional cell

#include "GCell.h"
#include <map>

class DPCell: public GCell {
 private:
  std::map<int,bool> local_signals;
  int proportion;

 public:

 /************************* Constructors ******************************/
  
  DPCell() { local_signals = std::map<int,bool>(); proportion = 0; }
 DPCell(std::map<int,bool> signalMap) : local_signals(signalMap) { proportion = 0; }

  
 /********************** Getters and Setters **************************/
  
  std::map<int,bool> getSignalsMap();
  int getProportion();
  void setProportion(int prop);
  
 /*********************** Auxiliary functions *************************/

  bool _existSignal(int id);

  
 /********************* Virtual member functions **********************/
  
  double getValue(int signal_id);
  void setValue(int signal_id, double concentration);
  void insertSignal(int id);
  void deleteSignal(int id);
  void incSignal(int id, double concentration);
  void decSignal(int id, double concentration);
};
