/*
 * Copyright (C) Sandra Sáez Raspeño - All Rights Reserved
 *
 * This file is part of Cellsignals.
 *
 * All information contained in this package is, and remains the property of
 * Sandra Sáez Raspeño. Copy and distribution of CellSignals or any result
 * generated by it is strictly forbidden unless prior written permission is
 * obtained from Sandra Sáez Raspeño.
 */

/**********************************************************************/
/*                                                                    */
/*                        ABSTRACT CELL CLASS                         */
/*                                                                    */
/**********************************************************************/

#ifndef GCELL_H
#define GCELL_H

class GCell {
 public:
  virtual double getValue(int) = 0;
  virtual void setValue(int, double) = 0;
  virtual void insertSignal(int) = 0;
  virtual void deleteSignal(int) = 0;
  virtual void incSignal(int, double) = 0;
  virtual void decSignal(int, double) = 0;
  virtual ~GCell() {}
};

#endif /* GCELL_H */
